---
--- Generated by Luanalysis
--- Created by PolyphonyRequiem.
--- DateTime: 7/30/2020 2:22 PM
---

local test = function()
    local ContentManager = require("src/ContentManager");

    local techDeckJson = [[      {
        "id": "technologies",
        "displayName": "Technologies",
        "tooltip": "The technologies available to a player to research",
        "frontUri": "https://timod.blob.core.windows.net/mod-assets/texture-atlases/faction-technologies-front.jpg",
        "backUri": "https://timod.blob.core.windows.net/mod-assets/texture-atlases/faction-technologies-back.jpg",
        "columns": 10,
        "rows": 6,
        "isSingleImageBack": false
      }]]

    ---@type DeckContentAsset
    local techDeck = JSON.decode(techDeckJson);

    ---@type ContentPackage
    local baseContent = {
        assets = {
            decks = {
                techDeck
            }
        }
    }

    local contentManager = ContentManager:new({baseContent});
    print(contentManager.contentSequence[1].assets.decks[1].id)
end

return test;
