---
--- Generated by Luanalysis
--- Created by PolyphonyRequiem.
--- DateTime: 7/30/2020 2:23 PM

---@class ContentManager
local ContentManager = {}

---@param contentSequence ContentPackage[]
---@return ContentManager
function ContentManager:new (contentSequence)
    local o = {contentSequence = contentSequence};
    setmetatable(o, self)
    self.__index = self
    return o
end

return ContentManager;
