---
--- Generated by Luanalysis
--- Created by PolyphonyRequiem.
--- DateTime: 7/30/2020 2:23 PM

---@class ContentManager
---@field contentSequence ContentPackage[]
local ContentManager = {}

---@return ContentManager
function ContentManager:new ()
  local o = {contentSequence = {}};
  setmetatable(o, self)
  self.__index = self
  return o
end

---@param contentPackage ContentPackage
function ContentManager:addContentPackage(contentPackage)
  table.insert(self.contentSequence, contentPackage);
end

---@return ContentPackage
function ContentManager:flatten ()
  return self.contentSequence[1];
end

return ContentManager;
