---
--- Generated by Luanalysis
--- Created by PolyphonyRequiem.
--- DateTime: 7/30/2020 2:23 PM
---

---@shape ContentPackage
---@field assets ContentPackageAssets

---@shape ContentPackageAssets
---@field decks DeckContentAsset[]

---@shape DeckContentAsset
---@field id string
---@field displayName string
---@field tooltip string
---@field frontUri string
---@field backUri string
---@field columns number
---@field rows number
---@field isSingleImageBack boolean
